### ISSUE TITLE
Allow dashes in filenames? 

### ISSUE THREAD

**Issue by rsdefever** [MaginnGroup/Cassandra#88]
Should we allow dashes in file names? This restriction occasionally causes confusion. I'm not opposed to disallowing dashes _if there is a good reason_. Otherwise, I think we should allow them. If we decide to make this change we need to make sure that dashes work with `mcfgen.py` and `library_setup.py` in addition to the core code.

@rwsmith7531 I know you have looked into this? 

@ryangmullen @emarinri Thoughts? 

## Describe the solution you'd like
Allow dashes in file names.

## Describe alternatives you've considered
Add an explicit warning in documentation. Also add a more descriptive error message to the code.

## Further information, files or links (optional)
Discussion spawned by #87.

**Comment by rwsmith7531** [comment]
I think we should allow dashes.  The part of the code that disallows them doesn't explicitly disallow them, but rather explicitly allows specific other characters, and dashes were likely not included due to an oversight.  I have briefly included them in the allowed characters and tested it on files with dashes in the past, and it worked fine.  Also, dashes are allowed in the input file name and the run name given in the input file, but are not allowed in the name of the file given in the Start Type section.

**Comment by rwsmith7531** [comment]
The part of the code responsible for it is in the subroutine `Check_String`, which starts at line 466 of `io_utilities.f90`.   The specific part of it begins at line 485 and is written as follows:
```
  DO i = 1, ncharacters
     IF ( .NOT. ((string_in(i:i) >=  'A' .AND. (string_in(i:i) <= 'Z')) .OR. &
          (string_in(i:i) >= 'a' .AND. (string_in(i:i) <= 'z')) .OR. &
          (string_in(i:i) >= '0' .AND. (string_in(i:i) <= '9')) .OR. &
          (string_in(i:i) == '.' .OR. string_in(i:i) == '_' .OR. string_in(i:i) == '/'))) THEN
        ! character other than letters and digits found
        ierr = 1
        RETURN
     END IF
  END DO
```
